version: '3.9'
services:
  nest-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  nest-app:
    build: .
    restart: always
    depends_on:
      - nest-db
    env_file:
      - .env
    ports:
      - '3000:3000'

volumes:
  postgres_data: # إضافة هذا السطر لتعريف الـ volume
